### ISSUE TITLE
[SUGGESTION] Virtualhere (Remote USB) support (preferably built-in)

### ISSUE THREAD

**Issue by MccallisterJ** [srevinsaju/guiscrcpy#116]
I've got it to work with SCRCPY before, but it's a pain. I assume a lot of people are like me and mostly use this for gaming on a larger screen or smaller sometimes ..(XBOX Streaming+Nvidia Shield+SCRCPY=XCloud on PC)  Since this is a program meant to simplify the use of SCRCPY, might as well include it for use with USB and bluetooth game controllers and the like. Especially when it soon will most likely be the primary way to connect to android from a remote PC on a different network, or at least I hope so. 

   (Kinda off topic, but still evolutionarily relevant) Anyone needing access to android TV from an outside network instead of using something like teamviewer, I find it easier to use Chrome Remote Desktop to SCRCPY. Now we just have to find a way to combine them into one seamless app with Virtualhere and I think we would have a winner..

**Comment by srevinsaju** [comment]
@MccallisterJ I had not heard of VirtualHere; I am not sure if its open source; can you post a link to VirtualHere's source code. I can only add support to commercial products with the help of open collective supporters; Adding support for commercial products within open source guiscrcpy will require some licensing work; and contacting members; 

When I get my first patron on [patreon](https://patreon.com/srevinsaju). I can give builds with VirtualHere support built in to patrons; So that I can avoid changing the open source code and retain my GNU GPL License. 

Thanks for using `guiscrcpy` and for your suggestions

**Comment by srevinsaju** [comment]
Here is the poll, https://www.patreon.com/posts/virtualhere-tm-36688180
