### ISSUE TITLE
Phone screen not showing

### ISSUE THREAD

**Issue by arnauldb** [srevinsaju/guiscrcpy#132]
**Describe the bug**
Phone screen not showing though I can swipe and interact with my phone using guiscrcpy arrows or guiscrcpy buttons.

**Screenshots**
![B7jQcdi](https://user-images.githubusercontent.com/13196747/81689120-8dc14b00-9449-11ea-94ce-05106b601360.png)

**Desktop (please complete the following information):**
* Linux Mint Sylvia 18.3
*Architecture*: 64-bit

**Linux**
 - Please paste your `neofetch` here. 
![foHcPRm](https://user-images.githubusercontent.com/13196747/81689585-f3add280-9449-11ea-9179-e13c678d5e43.png)

**Comment by srevinsaju** [comment]
@arnauldb Can you tell me how you installed `guiscrcpy' 
* AppImage?
* Snap
* Scrcpy

Did you try pressing `Start Scrcpy` button?

**Comment by srevinsaju** [comment]
@arnauldb Can you run `guiscrcpy` in terminal and let me know what is the output when you select your device in the device view and then execute `Start Scrcpy`.
If you do not see any errors, can you please do 
```bash
export GUISCRCPY_DEBUG=True
guiscrcpy
```
And could you paste the log in the console here so that I can identify what has gone wrong. 
Thanks
