### ISSUE TITLE
Forced close

### ISSUE THREAD

**Issue by TheMissionary** [srevinsaju/guiscrcpy#135]
Running 
Windows 10 64-bit Build 19628
guiscrcpy 3.8.5
OnePlus 8

I can successfully run scrcpy 1.13.  When start guiscrcpy, everything appears correct, my device is recognized, scrcpy server is recognized as running. I've got just a second before this error is presented and the program closes.  

Appreciate any leads.  Thanks!

![IMG_20200518_223049](https://user-images.githubusercontent.com/59755615/82288864-490d4680-9958-11ea-81b6-29f23db2001a.jpg)

**Comment by srevinsaju** [comment]
@TheMissionary can you please retry with v3.9? v3.9 included a lot of bug fixes, which can solve your problem in reality


By looking at your problem, I can see that either your adb or scrcpy is a corrupted application
If it still doesn't work with v3.9,
Please
* Remove `C:/Users/<username>/AppData/Local/guiscrcpy/guiscrcpy.json`
* Restart your computer
* Open guiscrcpy
* Check if typing adb and scrcpy in a powershell window works. (if it works, please let me know. Normally it should not. If it works, that means that you have another copy of adb or scrcpy on your PATH)
* Select the correct adb and scrcpy. 
* Run guiscrcpy and let me know the results


------------

What is your device architecture? Is it 64-bit? If it is, please make sure that the adb and scrcpy is also 64-bit, otherwise it might cause some errors

**Comment by TheMissionary** [comment]
Received.  I'll tighten down these items on my side this evening, and report back.  Thanks for the timely response!

**Comment by TheMissionary** [comment]
I removed all versions of adb and scrcpy, followed your instructions on the extra bits, reinstalled all fresh, including 3.9.  Your program works like a charm.  Thanks for your quick response!

**Comment by srevinsaju** [comment]
Glad to hear
