### ISSUE TITLE
[BUG] scrcpy not launch

### ISSUE THREAD

**Issue by mozgbrasil** [srevinsaju/guiscrcpy#151]
Good afternoon my friends

As the image does not launch scrcpy when clicking on the start button in guiscrcpy

![Captura de tela de 2020-06-25 19-45-25](https://user-images.githubusercontent.com/17202780/85803273-258aa800-b71d-11ea-8fe1-a44374ff2524.png)
![Captura de tela de 2020-06-25 19-44-24](https://user-images.githubusercontent.com/17202780/85803277-26233e80-b71d-11ea-81f9-d43c0c754881.png)
![Captura de tela de 2020-06-25 19-51-08](https://user-images.githubusercontent.com/17202780/85803317-3fc48600-b71d-11ea-85b5-42d3f3e79d30.png)

**Comment by srevinsaju** [comment]
@mozgbrasil sorry for the delay in reply.

Can you please remove 
```
~/.config/guiscrcpy
```
folder and try again?

**Comment by mozgbrasil** [comment]
Good Morning @srevinsaju 

Did not work  

![Captura de tela de 2020-06-29 11-14-34](https://user-images.githubusercontent.com/17202780/86016952-d0d77d80-b9f9-11ea-89f2-85878bebbbe8.png)
![Captura de tela de 2020-06-29 11-14-40](https://user-images.githubusercontent.com/17202780/86016954-d208aa80-b9f9-11ea-9bc0-09d68278be63.png)

**Comment by varadins** [comment]
When I click on "START SCRCPY" the tool bars appear, but it doesn't appear that scrcpy loads.  I don't see my android device.  When I run scrcpy - it works fine.

**Comment by ashishfeels** [comment]
same issue with ubuntu 20.04 @srevinsaju

**Comment by srevinsaju** [comment]
@ashishfeels @varadins how did you install `guiscrcpy` ?

**Comment by ashishfeels** [comment]
snap store @srevinsaju

**Comment by srevinsaju** [comment]
Hmm. I see; Please use AppImage, it will work then!

**Comment by ashishfeels** [comment]
will try

**Comment by ashishfeels** [comment]
not working for me @srevinsaju tried appImage

**Comment by jordond** [comment]
I've encountered this problem as well, and I've gotten around it by turning the screen on, and getting to the home screen (not lock screen). Then launching, and it works.

Worth a shot 🤷

**Comment by srevinsaju** [comment]
You are right! `scrcpy` sometimes fails to connect when phone is locked / permission is denied. Thanks @jordond 
Will add to the documentation!

**Comment by andrew-ayers** [comment]
I'm still having this issue - running Budgie Ubuntu 20.04 LTS - exactly the same thing @mozgbrasil showed with screenshots. Tried the trick of going to the home screen on phone, etc - `scrcpy` doesn't open a window. I installed the snap of `scrcpy` and I can launch it fine (I know that `guiscrcpy` has it's own version). I can provide more details if wanted/needed.

**Comment by srevinsaju** [comment]
You have to connect `:home` slot if you are installing guiscrcpy from snap. guiscrcpy cannot work without permission to write to home. This is one of the security features of snap.

Scrcpy wont start, when using guiscrcpy snap. This is because, `:adb` plug has to be connected to the snap. This is also a snap security feature. As the `:adb` plug is not connected, guiscrcpy cannot communicate to your device.

If you have scrcpy snap, and you might be running guiscrcpy as a snap or appimage (both snap and appimage has scrcpy bundled in by default), then scrcpy will not start when clicking "Start scrcpy". This is because, `scrcpy-snap`'s adb daemon might be running in the background. If thw adb of your system does not correspond to the latest adb version available from google' android developer tools, i t will fall into a conflict.

I can you provide you a solution.

* install guiscrcpy without bundled scrcpy. 

Install a version of guiscrcpy, where I have not bundled scrcpy in it. This would work for sure (as you said scrcpy works, but guiscrcpy doesn't), but the method of installation is different

```bash
pip install https://github.com/srevinsaju/guiscrcpy/archive/master.zip```

Should install a standalonw version of guiscrcpy, running on plain barebones

* Use AppImage v4.4.0 (continuous) tag. The new appimage should solve this problem.
To communicate with scrcpy or adb which are bundled within the AppImage, you could just do 

```bash
guiscrcpy adb devices
```
to list all devices 

Or 
```
guiscrcpy scrcpy
```
To start the bundled scrcpy

I do not prefer snaps, as its too security oriented. I wish that someone would create a deb for guiscrcpy and publiah it so that, one could run 

```
sudo apt install guiscrcpy
```

Easy as pie


* third option, (not recommended, worth a try), install guiscrcpy snap from `edge` channel

```
[sudo] snap install guiscrcpy --edge
```

This would install guiscrcpy 4.4.0, and thwn you can check if scrcpy starts by running

```
guiscrcpy scrcpy
```

**Comment by srevinsaju** [comment]
Assuming, this is fixed. I am closing this issue. If problem persists even with the latest release, please reopen this issue or create a new issue. Thanks to all who tested it.

FYI, `scrcpy` will sometimes take `time` to launch. This is because your phone screen might be switched off. If you switch on the phone screen yourself, the scrcpy window will appear faster.
