### ISSUE TITLE
How to create Desktop Shortcut in Windows?

### ISSUE THREAD

**Issue by levirs565** [srevinsaju/guiscrcpy#204]
I am install guiscrcpy with pip. I am using python3. How to create desktop shorcut?. I am using Windows 10

**Comment by srevinsaju** [comment]
Currently, I am looking for a method to do that too. One solution is to create a batch script

1. Open notepad or any other text editor
2. Type into it
```batch
python -m guiscrcpy.cli
```
3. Save it as `guiscrcpy-launcher.bat`, don't forget to select `All Files (.*)` in the save drop down menu, otherwise your batch script will be saved as `.txt` format.
4. Now, double click on this batch script and see if it works.
5. It works? :tada: 
6. Right click > Add shortcut to desktop
7. Set Icon and enjoy

**Comment by levirs565** [comment]
I found that GuiScrCpy has a built-in shortcut maker. I run python, then type this:
```
from guiscrcpy.platform.windows_tools.tools import make_shortcut
```

Shortcut Will created in desktop and application list. However there are problems like the following

- The icon file `guiscrcpy/ui/icons/guiscrcpy_logo_SRj_icon.ico` not found. This because the file is not shipped in package. This make shortcut does not have an icon.
- A console window (`cmd.exe`) is appear

**Comment by srevinsaju** [comment]
> I found that GuiScrCpy has a built-in shortcut maker. I run python, then type this:
> 

cool

> ```
> from guiscrcpy.platform.windows_tools.tools import make_shortcut
> make_shortcut()
> ```
> 
> Shortcut Will created in desktop and application list. However there are problems like the following
> 
> * The icon file `guiscrcpy/ui/icons/guiscrcpy_logo_SRj_icon.ico` not found. This because the file is not shipped in package. This make shortcut does not have an icon. Ship this file in package should fix this problem.

The icon is shipped with the package. See [this](https://github.com/srevinsaju/guiscrcpy/blob/master/guiscrcpy/ui/icons/guiscrcpy_logo_SRj_icon.ico)

> * A console window (`cmd.exe`) is appear

Don't know why. Any solutions?

**Comment by levirs565** [comment]
I have create pull request to fix this issue https://github.com/srevinsaju/guiscrcpy/pull/205
