### ISSUE TITLE
Build 0.0.0

### ISSUE THREAD

**Issue by yochananmarqos** [srevinsaju/guiscrcpy#53]
With the 3.0 release, building from the master branch or the release tag, the build now shows 0.0.0. Pulling from master was showing the actual build number earlier.

Building from GitHub there's no errors, but building from the PyPI release package there are:

```
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/yochanan/Documents/AUR/guiscrcpy/src/guiscrcpy-3.0/README.md'
```

I renamed `README.rst` to `README.md` and then:

```
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    version=repo.git.describe("--tags"),
  File "/usr/lib/python3.8/site-packages/git/cmd.py", line 551, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/git/cmd.py", line 1020, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/lib/python3.8/site-packages/git/cmd.py", line 831, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git describe --tags
  stderr: 'fatal: No names found, cannot describe anything.'
```

There's got to be a better way to read the version than using GitPython.

**Comment by srevinsaju** [comment]
Yes @yochananmarqos , thats because the PYPI package is built from github repo, it requires manual patching to fix that if you are trying to build from PYPI release, here's how:
* remove all of git imports, and replace `version=repo.git.describe("--tags")` with `version=3.0` if you are manually building it from AUR. The `repo.git.decribe` checks the .git directory (which does not exist on a PYPI release). This was done to reduce my work of editing setup.py for every release.

Temporily, if building from master shows `0.0.0`, the `[:-9]` part should be removed off:
https://github.com/srevinsaju/guiscrcpy/blob/02783c8d537d183a47743f429987b6dc09b9a11d/setup.py#L19

The README can be ignored for AUR

**Comment by yochananmarqos** [comment]
Thanks for the tips, perhaps I'll try that. However, building from master also shows 0.0.0 when it did not before.

**Comment by srevinsaju** [comment]
it didn't happen to me when I tried, but I saw this error previously, will give a fix for it

**Comment by srevinsaju** [comment]
@yochananmarqos I guess I fixed it on https://github.com/srevinsaju/guiscrcpy/commit/491c478dbe5da015419abba00bdcfa507311fb33, but now will have to wait for another tag to see if it actually works. Now the version should be `v3.0-1` and not `v3.0`

**Comment by yochananmarqos** [comment]
Thanks, now it shows 3.0.post1.

**Comment by srevinsaju** [comment]
Yea :)

**Comment by yochananmarqos** [comment]
Unrelated question: Is setuptools a runtime dependency or only for setup?

**Comment by srevinsaju** [comment]
Its only for the setup

**Comment by yochananmarqos** [comment]
Still getting this error pulling from that commit directly:

```
/usr/lib/python3.8/site-packages/setuptools/dist.py:481: UserWarning: The version specified ('') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
```

It doesn't make any sense since pulling from master is the exact same commit. I wonder if it's how `makepkg` uses `git`.

**Comment by yochananmarqos** [comment]
Alright, now it's all sorted. The stable `guiscrcpy` AUR package now displays `3.0` patching `setup.py` like you recommended.

**Comment by srevinsaju** [comment]
https://github.com/srevinsaju/guiscrcpy/blob/491c478dbe5da015419abba00bdcfa507311fb33/guiscrcpy/lib/ver.py#L79-L81

@yochananmarqos , you can alternatively change what is displayed on the main window, for example:
now it shows `v3.0 by srevinsaju`, but you can edit and modify it to show `v3.0 AUR by yochananmarqos`. after v3 it has become easy for packagers to brand guiscrcpy, it might help you in future builds

**Comment by yochananmarqos** [comment]
I'm a packager, not the developer. You get the credit, not me. ;)

Any idea why it does this during setup?

```
/usr/lib/python3.8/site-packages/setuptools/dist.py:473: UserWarning: Normalizing '3.0-8' to '3.0.post8'
  warnings.warn(
```

**Comment by srevinsaju** [comment]
@yochananmarqos , Yup, thats because, we are not supposed to create a version on pypi, with `v3.0-8` because the hyphen on python means subtraction, thats odd, but instead we should use `v3.0.post8`, thats the correct way to do it. But Python package manager automatically does that, when we install a package like that.
