### ISSUE TITLE
NameError: name 'FileNotFoundError' is not defined

### ISSUE THREAD

**Issue by linuxundich** [srevinsaju/guiscrcpy#8]
I installed guiscrcpy under Arch Linux (via AUR guiscrcpy aswell as guiscrcpy-git). Both versions fail at the with the following error...

    $ guiscrcpy 
    ************************************
    guiscrcpy v1.10.0-release           
    by srevinsaju                       
    ************************************
    released on 24082019 GMT+0300 2048  
    Licensed under GNU GPL v3 (c) 2019  
    ************************************
    Traceback (most recent call last):
      File "/opt/guiscrcpy/__main__.py", line 137, in <module>
        except FileNotFoundError or FileExistsError:
    NameError: name 'FileNotFoundError' is not defined

My system is up to date, I'm using Gnome 3.32 as desktop environment.

**Comment by Strubbl** [comment]
Which is your default python version? 
You can find out with `python --version`

**Comment by linuxundich** [comment]
Yeah, Python2...

    $ python --version
    Python 2.7.16

**Comment by Strubbl** [comment]
guiscrcpy needs python3. I do not know if it can be required by the AUR package somehow.

```
$ cat /usr/bin/guiscrcpy 
#!/bin/bash
python /opt/guiscrcpy/__main__.py
```

So, if you have python3 installed and start guiscrcrpy with `python3 /opt/guiscrcpy/__main__.py`, it should work.

**Comment by linuxundich** [comment]
Thanks for your help! I had a Python2-Binary in my $PATH. Don't remember why, but I deleted it and rebuilt the program. It "works" now... in other words: it crashes, but with another error. I'll open another issue

**Comment by srevinsaju** [comment]
Why does the binary file not work, even though you have python 2, python3 lib.so libraries are also embedded, so that you can run this anywhere. 
(I) did you try 19.04 v or 18.04 v 
(II) can you give the output while running binary?

@Strubbl, how did you understand it's a python2 output, hatsoff to your skills, I am a newbie :)

**Comment by linuxundich** [comment]
@Strubbl The second time I started `guiscrcpy` everything works. Will play with your tool for a while :+1:

**Comment by Strubbl** [comment]
The binary file did not work, because it calls python. Due to the changed linuxundich's $PATH variable the python command pointed out to a python2 binary.

Usually in a default Archlinux installation, python shall point to python3, e.g.:

```
$ type python
python is /usr/bin/python
$ ls -l /usr/bin/python
lrwxrwxrwx 1 root root 7 Jul 16 09:12 /usr/bin/python -> python3*
```

I am no python expert, but i googled, and saw the FileNotFoundError was not part of python2.

**Comment by srevinsaju** [comment]
@Strubbl, thanks for the info! Me too, I am neither a python expert, a grade 11 student.
So I learnt a bit today though :).

Seems like I have to update the README.md and reference this issue. Thanks 😊
